### ISSUE TITLE
Probably wrong Schematic (first, 7seg)

### ISSUE THREAD

**Issue by KoolKeith** [gavinlyonsrepo/FourteenSegDisplay#1]
Hello dear library author,
I've been studying your schematic this whole evening. I wanted to wire up everything first (in fritzing), so I have not even tried the software. First of all, most docs on the net refer to the clock/latch pins differently. I have found out these relations/mappings on the 595:

```
PIN-No	YourName	ModernName
--------------------------------------
10	?		MR
11	SCLK		SH_CP
12	RCLK		ST_CP
```
I don't know if your name is newer or older than everybody elses, but it seems to be uncommon. 

Now, the first problem is... in the schematic you introduce "SCK" and "SCL". But the real knockdown problem to me is: "Pin 10 (?!), which is pulled high (?!) and called SCL (!!!!).

I think you meant MR here... 

Please, I am really confused ! Could you use names which are logically definite, and clear this confusion up? Your lib looks perfect for me !

I am pretty new and this time I wanted to research and understand it all properly. I like your project and setup. It's nice that you consequently use just 3 MC pins, paying it with another 595 (thats good!). Also the code does not seem to have any timing complexities. But I guess I'll see when I actually append this stuff to by OTA-Enabled base sketch.

I also attach my own documentation, which I taylored to fit your schematic (greyed out are alternative names, STCP and SHCP probably more common).

![image](https://user-images.githubusercontent.com/10271212/236654940-c317ab64-303a-4d90-a3dc-fe5e3773b444.png)

![image](https://user-images.githubusercontent.com/10271212/236654956-f92f21bf-373e-49c4-89b3-8dbf79654840.png)

Have a nice day ! Don't take my approach as an offense :)

**Comment by gavinlyonsrepo** [comment]
Hi 

|Arduino pin label | Schematic label IC | TI Datasheet label | pin number |
|--------|--------|--------| --------|
| RCLK | RCK |RCLK |12  |
| SCLK | SCK | SRCLK |11 |
| n/a | SCL | SRCLR | 10  |

The schematic pins labels in the standard eagle library for this pinout package are abbreviated 
for clarity and compactness.  There is no error. 

![TI_datasheet](https://user-images.githubusercontent.com/21970139/236673760-1f58aa28-7856-4480-83eb-dd45ef375ade.png)

Texas instruments datasheet 
https://www.ti.com/lit/ds/symlink/sn74hc595.pdf

I will change the markdown tables in README  so they match the schematic  label and not the code label. Not much point changing the code.

**Comment by KoolKeith** [comment]
Cool, thank you. I understand it now ! :)
